#!/bin/bash
ROOT="/simtalk"
CURR_ROOT=$(pwd)
INCLUDE_PATH=$CURR_ROOT/include
LIB_PATH=$CURR_ROOT/lib

#[[-----*set environment variables*-----]]

#common Makefile path
export MAKE_COMMON=$CURR_ROOT/common.mk

#gcc include path
C_INCLUDE_PATH="${C_INCLUDE_PATH}:${INCLUDE_PATH}"
export C_INCLUDE_PATH=$C_INCLUDE_PATH

#g++ include path
CPLUS_INCLUDE_PATH="${CPLUS_INCLUDE_PATH}:${INCLUDE_PATH}"
export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH

#dynamic link library path
LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${LIB_PATH}"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH

#static library path
LIBRARY_PATH="${LIBRARY_PATH}:${LIB_PATH}"
export LIBRARY_PATH=$LIBRARY_PATH
