#!/bin/bash
ROOT="/simtalk"
CURR_ROOT=$(pwd)
INCLUDE_PATH=$CURR_ROOT/include
LIB_PATH=$CURR_ROOT/lib

#[[-----*set environment variables*-----]]

#common Makefile path
export MAKE_COMMON=$CURR_ROOT/common.mk

#C include path
C_INCLUDE_PATH="${INCLUDE_PATH}"
export C_INCLUDE_PATH=$C_INCLUDE_PATH

#C++ include path
CPLUS_INCLUDE_PATH="${INCLUDE_PATH}"
export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH

#shared dynamic link library path
LD_LIBRARY_PATH="${LIB_PATH}/lib.so/"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH

#static library path
LIBRARY_PATH="${LIB_PATH}/lib.a/"
export LIBRARY_PATH=$LIBRARY_PATH
